[TAIPY]

[DATA_NODE.image_path]

[DATA_NODE.model]

[DATA_NODE.prediction_result]

[DATA_NODE.explain]

[TASK.predict_image]
function = "__main__.predict_image:function"
inputs = [ "image_path:SECTION", "model:SECTION", "explain:SECTION",]
outputs = [ "prediction_result:SECTION",]
skippable = "False:bool"

[SCENARIO.image_prediction_scenario]
tasks = [ "predict_image:SECTION",]
additional_data_nodes = []

[SCENARIO.image_prediction_scenario.comparators]

[SCENARIO.image_prediction_scenario.sequences]
